# Loading super confidential stuff
source "$HOME/.dream-terminal/zsh/super_confidential/private.sh"

# (option/alt)+> (option/alt)+< navigate by words
bindkey "^[[1;3C" forward-word
bindkey "^[[1;3D" backward-word

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Fig pre block. Keep at the top of this file.
[[ -f "$HOME/.fig/shell/zshrc.pre.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.pre.zsh"

# RUBY setup
export RUBY_CONFIGURE_OPTS="--with-openssl-dir=$(brew --prefix openssl@1.1)"
export RBENV_ROOT="$(brew --prefix rbenv)"
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"
export PATH="$HOME/.gem/ruby/2.7.0/bin:$PATH"

#Maven setup
export PATH="$HOME/.development/apache-maven/bin:$PATH"

#Optional Maven setup
export MAVEN_OPTS="--add-opens=java.base/java.util=ALL-UNNAMED"

#Flutter
export PATH="$HOME/.development/flutter/bin:$PATH"

# !! MAC OS !!
#Python
export PATH="$HOME/Library/Python/3.8/bin:$PATH"
export PATH=/usr/local/bin:$PATH

# !! MAC OS !!
#Android
export ANDROID_HOME="$HOME/Library/Android/sdk"
export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"

# !! MAC OS !!
# Java versions
alias java17="export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
alias java16="export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-16.jdk/Contents/Home"
alias java11="export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home"
alias java8="export JAVA_HOME=/Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home"
alias corretto17="export JAVA_HOME=/Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home"

# Enable my default Java versions
corretto17

# Git custom commands
alias git-tree="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset%n' --abbrev-commit --date=relative --branches"

#ZSH config
export ZSH="$HOME/.config/zsh/.oh-my-zsh"

# Other ZSH themes
# ZSH_THEME="gozilla"
# ZSH_THEME="josh"
# ZSH_THEME="frisk"
# ZSH_THEME="refined"
# ZSH_THEME="Soliah"

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
plugins=(git gitfast vscode ruby python docker macos zsh-autosuggestions zsh-syntax-highlighting zsh-completions)

source $ZSH/oh-my-zsh.sh
source $ZSH/sudo.plugin.zsh

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Replace vim with NVIM
alias vim="nvim"

# !! MAC OS !!
# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/opt/homebrew/Caskroom/miniforge/base/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
eval "$__conda_setup"
else
if [ -f "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh" ]; then
. "/opt/homebrew/Caskroom/miniforge/base/etc/profile.d/conda.sh"
else
export PATH="/opt/homebrew/Caskroom/miniforge/base/bin:$PATH"
fi
fi
unset __conda_setup
# <<< conda initialize <<<

# Load Angular CLI autocompletion.
source <(ng completion script)

# Fig post block. Keep at the bottom of this file.
[[ -f "$HOME/.fig/shell/zshrc.post.zsh" ]] && builtin source "$HOME/.fig/shell/zshrc.post.zsh"

# cat commnad replacement with bat
alias cat="bat"

# ls command replacement qith lsd
alias ls="lsd"

# get public ip command
alias public-ip="curl ifconfig.me"

# adding safe delete function
# especial thanks to s4vitar for this safe delete technique
# https://github.com/s4vitar
function rmk() {
    scrub -p dod $1
    gshred -zun 10 -v $1 # MAC
    #shred -zun 10 -v $1 # LINUX
}

# To customize prompt, run `p10k configure` or edit $HOME/.p10k.zsh.
[[ ! -f "$HOME/.p10k.zsh" ]] || source "$HOME/.p10k.zsh"
source "$HOME/powerlevel10k/powerlevel10k.zsh-theme"
